---
layout: techpost
title: Gradle `Unable to establish loopback connection` resolved
---

So all of a sudden I began having issues with Gradle 1.6 builds failing, and this time not because of my code. I was getting errors like this: <br /><br /><pre>org.gradle.process.internal.ExecException: Timeout after waiting 120.0 seconds for Gradle Worker 6 (STARTED, running: true) to connect.<br />        at org.gradle.process.internal.DefaultWorkerProcess.doStart(DefaultWorkerProcess.java:137)<br />        at org.gradle.process.internal.DefaultWorkerProcess.start(DefaultWorkerProcess.java:114)<br />        at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.processTestClass(ForkingTestClassProcessor.java:63)<br />        at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:45)<br />        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br />        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />        at java.lang.reflect.Method.invoke(Method.java:601)<br />        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)<br />        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)<br />        at org.gradle.messaging.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)<br />        at org.gradle.messaging.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:132)<br />        at org.gradle.messaging.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:33)<br />        at org.gradle.messaging.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:72)<br />        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:66)<br />        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br />        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br />        at java.lang.Thread.run(Thread.java:722)<br />Could not accept remote connection.<br />org.gradle.internal.UncheckedException: java.io.IOException: Unable to establish loopback connection<br />        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:39)<br />        at org.gradle.messaging.remote.internal.inet.SocketConnection.<init>(SocketConnection.java:58)<br />        at org.gradle.messaging.remote.internal.inet.TcpIncomingConnector$Receiver.run(TcpIncomingConnector.java:119)<br />        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:66)<br />        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br />        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br />        at java.lang.Thread.run(Thread.java:722)<br />Caused by: java.io.IOException: Unable to establish loopback connection<br />        at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:125)<br />        at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:69)<br />        at java.security.AccessController.doPrivileged(Native Method)<br />        at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:141)<br />        at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)<br />        at java.nio.channels.Pipe.open(Pipe.java:150)<br />        at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:126)<br />        at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)<br />        at java.nio.channels.Selector.open(Selector.java:227)<br />        at org.gradle.messaging.remote.internal.inet.SocketConnection$SocketInputStream.<init>(SocketConnection.java:135)<br />        at org.gradle.messaging.remote.internal.inet.SocketConnection.<init>(SocketConnection.java:56)<br />        ... 5 more<br />Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host<br />        at sun.nio.ch.SocketDispatcher.read0(Native Method)<br />        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)<br />        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:225)<br />        at sun.nio.ch.IOUtil.read(IOUtil.java:198)<br />        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:359)<br />        at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:108)<br />        ... 15 more</init></init></init></init></init></pre><br />Turns out that Windows|Anti-Virus was preventing Java 1.7.0_21 from doing any networking, presumably due to some security problem. Changing JAVA_HOME to 1.7.0_25 did the trick. 
